#config['references'][wildcards.ref_set]['prefix']

samples_fp: 'samples.txt'

references:
  genome_list: 'Test/references.txt'
  drep:
    prodigal: 'Test/drep/dereplicated_genomes'
    derep_genomes: 'Test/drep/data/prodigal'

params:
  bowtie2:
    index: ''
    map: ''
  instrain:
    profile: ''     
    compare: ''
  bakta:
    db_path: '/panfs/j4sanders/dbs/bakta'
    other: ''