#config['references'][wildcards.ref_set]['prefix']

samples_fp: 'samples.txt'

resources: 'Resources/resources.yaml'

references:
  genome_list: 'Tests/local_genomes.txt'
  drep:
    prodigal: 'Tests/drep/dereplicated_genomes'
    derep_genomes: 'Tests/drep/data/prodigal'

params:
  bowtie2:
    index: ''
    map: ''
  instrain:
    profile: ''     
    compare: ''
  bakta:
    db_path: '/panfs/j4sanders/dbs/bakta'
    tmp_dir: 'output/annotate/bakta/tmp'
    other: ''