#config['references'][wildcards.ref_set]['prefix']

references:
  local:
    prefix: 'local'
    genome_list: 'Tests/local_genomes.txt'
  remote:
    prefix: 'remote'
    genome_list: 'Tests/remote_genomes.txt'