#config['references'][wildcards.ref_set]['prefix']

samples_fp: 'samples.txt'

references:
  local:
    prefix: 'local'
    genome_list: 'Tests/local_genomes.txt'
  remote:
    prefix: 'remote'
    genome_list: 'Tests/remote_genomes.txt'

params:
  drep:
    sa: 95
    other: ''
    threads: 12
  bowtie2:
    threads: 4
    index: ''
    map: ''